from pathlib import Path
import subprocess, tempfile, os, shutil
root=Path(__file__).resolve().parents[2]
pkg='com.nezurstandalone' if (root/'src/main/java/com/nezurstandalone').exists() else 'com.nezur'
java_home=os.environ.get('JAVA_HOME','')
javac=str(Path(java_home)/'bin/javac.exe') if java_home else shutil.which('javac')
java=str(Path(java_home)/'bin/java.exe') if java_home else shutil.which('java')
if not javac or not java: raise SystemExit('Set JAVA_HOME to a JDK 8 installation')
common={
'net/minecraft/client/Minecraft.java':'''package net.minecraft.client; public class Minecraft {static final Minecraft M=new Minecraft();public static Minecraft getMinecraft(){return M;} public net.minecraft.world.World theWorld;public net.minecraft.entity.player.EntityPlayer thePlayer;public Object currentScreen;public Settings gameSettings=new Settings();public net.minecraft.util.MovingObjectPosition objectMouseOver;public static class Settings{public net.minecraft.client.settings.KeyBinding keyBindSneak=new net.minecraft.client.settings.KeyBinding();}}''',
'net/minecraft/client/settings/KeyBinding.java':'''package net.minecraft.client.settings; public class KeyBinding {public static boolean down;public int getKeyCode(){return 42;}public static void setKeyBindState(int k,boolean b){down=b;}}''',
'net/minecraft/world/World.java':'''package net.minecraft.world;public class World{public java.util.List<net.minecraft.entity.Entity> loadedEntityList=new java.util.ArrayList<>();public java.util.List<net.minecraft.entity.player.EntityPlayer> playerEntities=new java.util.ArrayList<>();}''',
'net/minecraft/entity/Entity.java':'''package net.minecraft.entity;public class Entity{public boolean isDead;public net.minecraft.world.World worldObj;public double posX,posY,posZ;public float getDistanceToEntity(Entity e){return (float)Math.abs(posX-e.posX);}public boolean hasCustomName(){return false;}public String getCustomNameTag(){return "";}}''',
'net/minecraft/entity/item/EntityArmorStand.java':'''package net.minecraft.entity.item;public class EntityArmorStand extends net.minecraft.entity.Entity{}''',
'net/minecraft/entity/player/EntityPlayer.java':'''package net.minecraft.entity.player;public class EntityPlayer extends net.minecraft.entity.Entity{public int ticksExisted;public boolean using;public float health=20;public float getHealth(){return health;}public boolean isUsingItem(){return using;}public boolean isSneaking(){return net.minecraft.client.settings.KeyBinding.down;}public net.minecraft.item.ItemStack getHeldItem(){return null;}public net.minecraft.util.Vec3 getPositionEyes(float f){return new net.minecraft.util.Vec3(posX);}public Inventory inventory=new Inventory();public static class Inventory{public net.minecraft.item.ItemStack[] armorInventory=new net.minecraft.item.ItemStack[4];}}''',
'net/minecraft/item/Item.java':'''package net.minecraft.item;public class Item{public static int getIdFromItem(Item i){return 276;}}''',
'net/minecraft/item/ItemStack.java':'''package net.minecraft.item;public class ItemStack{public Item getItem(){return null;}}''',
'net/minecraft/util/Vec3.java':'''package net.minecraft.util;public class Vec3{public double x;public Vec3(double x){this.x=x;}public double distanceTo(Vec3 v){return Math.abs(x-v.x);}}''',
'net/minecraft/util/MovingObjectPosition.java':'''package net.minecraft.util;public class MovingObjectPosition{public enum MovingObjectType{ENTITY,BLOCK,MISS}public MovingObjectType typeOfHit=MovingObjectType.ENTITY;public net.minecraft.entity.Entity entityHit;public Vec3 hitVec;}''',
'net/minecraft/util/StringUtils.java':'''package net.minecraft.util;public class StringUtils{public static String stripControlCodes(String s){return s;}}'''}
pp=pkg.replace('.','/');stubs=dict(common);stubs.update({pp+'/input/NativeActionGate.java':'package PKG.input;public class NativeActionGate{public static boolean held;public static boolean physical(int k){return held;}}',pp+'/control/Clock.java':'package PKG.control;public class Clock{public static long now=1000;public static long millis(){return now;}}',pp+'/utils/PitMapManager.java':'package PKG.utils;public class PitMapManager{public static String zone="Pit";public static String getZone(double x,double y,double z){return zone;}}',pp+'/Nezur.java':'package PKG;public class Nezur{public static Manager moduleManager;public static class Manager{public <T>T getModuleByClass(Class<T> c){return null;}}}',pp+'/module/impl/player/AutoGrinder.java':'package PKG.module.impl.player;public class AutoGrinder{public boolean isTemporaryNoPerkReady(){return true;}}',pp+'/contract/ContractOffer.java':'package PKG.contract;public class ContractOffer{public enum Type{KILL_PLAYERS,FIST_MID_KILLS,SNEAK_ATTACK_KILLS,NO_ARMOR_KILLS,NO_PERK_KILLS,DIAMOND_SWORD_FINAL_BLOW,CHAIN_KILLS,CLAIM_BOUNTIES,COLLECT_GOLD_INGOTS,KILL_STREAK,GOLDEN_APPLES}}'})
test='''import PKG.contract.*;import PKG.control.Clock;import PKG.utils.PitMapManager;import net.minecraft.client.*;import net.minecraft.client.settings.*;import net.minecraft.entity.player.*;import net.minecraft.util.*;
public class SneakRegression {static Minecraft mc=Minecraft.getMinecraft();static EntityPlayer target;static boolean modified;static void reset(){mc.theWorld=new net.minecraft.world.World();mc.thePlayer=new EntityPlayer();mc.thePlayer.worldObj=mc.theWorld;target=new EntityPlayer();target.worldObj=mc.theWorld;target.posX=3;mc.currentScreen=null;PitMapManager.zone="Pit";PKG.input.NativeActionGate.held=false;mc.objectMouseOver=new MovingObjectPosition();mc.objectMouseOver.entityHit=target;mc.objectMouseOver.hitVec=new Vec3(3);ContractCombatPolicy.install(ContractOffer.Type.SNEAK_ATTACK_KILLS,100,3.5);Clock.now=1000;mc.thePlayer.ticksExisted=100;}
static void update()throws Exception{try{ContractCombatPolicy.class.getMethod("updateSneak").invoke(null);}catch(NoSuchMethodException baseline){}}
static void check(String name,boolean expected){System.out.println(name+"="+KeyBinding.down);if(modified&&KeyBinding.down!=expected)throw new AssertionError(name);}
static void start(){ContractCombatPolicy.allowsAttack(target);Clock.now+=151;mc.thePlayer.ticksExisted+=3;}
public static void main(String[] a)throws Exception{modified=a[0].equals("modified");reset();ContractCombatPolicy.allowsAttack(target);Clock.now+=151;boolean zero=ContractCombatPolicy.allowsCrosshairAttack();mc.thePlayer.ticksExisted+=2;boolean two=ContractCombatPolicy.allowsCrosshairAttack();mc.thePlayer.ticksExisted++;boolean three=ContractCombatPolicy.allowsCrosshairAttack();System.out.println("CLICK_GATE ticks0="+zero+" ticks2="+two+" ticks3="+three);if(modified&&(zero||two||!three))throw new AssertionError("three tick gate");reset();start();check("near-hit-sneak",true);if(!ContractCombatPolicy.allowsCrosshairAttack())throw new AssertionError("close hit after delay");target.posX=3.6;mc.objectMouseOver.hitVec=new Vec3(3.6);update();check("far-target-sneak",false);if(modified&&ContractCombatPolicy.allowsCrosshairAttack())throw new AssertionError("far hit");reset();start();PitMapManager.zone="Spawn";update();check("spawn-sneak",false);reset();start();mc.objectMouseOver=null;update();check("no-crosshair-sneak",true);if(!ContractCombatPolicy.allowsCrosshairAttack())throw new AssertionError("click cadence across crosshair gap");reset();start();mc.currentScreen=new Object();update();check("gui-sneak",false);reset();start();mc.thePlayer.using=true;update();check("healing-sneak",false);reset();start();target.isDead=true;update();check("dead-target-sneak",false);reset();start();mc.theWorld=new net.minecraft.world.World();update();check("world-change-sneak",false);reset();start();ContractCombatPolicy.noTarget();check("pause-sneak",false);reset();mc.objectMouseOver.hitVec=new Vec3(4);ContractCombatPolicy.allowsAttack(target);check("unreachable-ray-sneak",false);reset();start();PKG.input.NativeActionGate.held=true;target.posX=4;update();check("physical-user-sneak-preserved",true);System.out.println("REGRESSION="+a[0]+" PASS");}}
'''

with tempfile.TemporaryDirectory(prefix='nezur-sneak-regression-') as temp:
 folder=Path(temp)
 for path,content in stubs.items():
  f=folder/path;f.parent.mkdir(parents=True,exist_ok=True);f.write_text(content.replace('PKG',pkg),encoding='utf-8')
 source=root/'src/main/java'/pp/'contract/ContractCombatPolicy.java'
 (folder/pp/'contract/ContractCombatPolicy.java').write_bytes(source.read_bytes())
 (folder/'SneakRegression.java').write_text(test.replace('PKG',pkg),encoding='utf-8')
 classes=folder/'classes';classes.mkdir()
 subprocess.run([javac,'-source','8','-target','8','-d',str(classes),*map(str,folder.rglob('*.java'))],check=True)
 subprocess.run([java,'-cp',str(classes),'SneakRegression','modified'],check=True)
